import { Foco } from "@/lib/fonts";
import "./globals.css";
import Provider from "@/store/Provider";

export const metadata = {
  title: "KnowCrunch",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Foco.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
