import { Foco } from "@/lib/fonts";
import "./globals.css";

export const metadata = {
  title: "KnowCrunch",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Foco.className}>
        {children}
      </body>
    </html>
  );
}
