import { Foco } from "@/lib/fonts";
import { ThemeProvider } from "@mui/material/styles";
import "./globals.css";
import Provider from "@/store/Provider";
import theme from "@/theme";

import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
export const metadata = {
  title: "KnowCrunch",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={Foco.className}>
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider theme={theme}>
            <Provider>{children}</Provider>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
