name: Deploy on Staging Server
on:
  push:
    branches:
      - main
jobs:
  push_event:
    name: Deploy on Staging Server
    runs-on: knowcrunch-fe
    steps:
      - uses: actions/checkout@v3
      - name: set-UP
        run: |
          cd /home/knowcrunch-fe/knowcrunch
          git pull
          npm install
          npm run build
          pm2 restart all --time
          exit
